---

- hosts: localhost

  vars:
      - httpd
      - binutils
      - glibc
      - ksh
      - libaio
      - libXext
      - gcc
      - make
      - sysstat
      - unixODBC
      - mongodb
      - nodejs
      - grunt

  tasks:
    - yum:
      name: "{{ item }}"
      state: present
      with_items: "{{ packages }}"
      register: myoutput
    
    - debug: var=mnt
