---
- hosts: localhost
  connection: local
 
  vars:
    fruits:
      - Apple
      - Banana
      - Orange
      - Grapes
 
  tasks:
    - command: echo "{{ item }}"
      with_items: '{{ fruits }}'

    - debug: msg="{{ item }}"
      with_items: '{{ fruits }}'

